/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example.View.FeeRelated;

import javax.swing.*;

/**
 *
 * @author negas
 */
public class FeeView extends javax.swing.JFrame {

    JDialog activityFee = new JDialog();
    JDialog cabinFee = new JDialog();
    JDialog campingFee = new JDialog();
    
    
    public FeeView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        feeTitle = new javax.swing.JLabel();
        feeButtonQueryCabin = new javax.swing.JButton();
        feeButtonQueryCamping = new javax.swing.JButton();
        feeButtonQueryActivities = new javax.swing.JButton();
        feeButtonReturn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        feeTitle.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        feeTitle.setText("Consultar tarifas");

        feeButtonQueryCabin.setText("Cabañas");
        feeButtonQueryCabin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feeButtonQueryCabinActionPerformed(evt);
            }
        });

        feeButtonQueryCamping.setText("Campings");

        feeButtonQueryActivities.setText("Actividades");

        feeButtonReturn.setText("Salir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(feeButtonQueryCabin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(feeButtonQueryCamping, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addComponent(feeButtonQueryActivities))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(feeTitle)))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(feeButtonReturn))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(feeTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(feeButtonQueryCabin)
                    .addComponent(feeButtonQueryActivities))
                .addGap(18, 18, 18)
                .addComponent(feeButtonQueryCamping)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(feeButtonReturn))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void feeButtonQueryCabinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feeButtonQueryCabinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_feeButtonQueryCabinActionPerformed
    
    // Métodos
    public void showCabinFee(String message) {
        javax.swing.JOptionPane.showMessageDialog(this, message, "Tarifa de cabañas", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }
    
    public void showActivityFee(String message){
        javax.swing.JOptionPane.showMessageDialog(this, message, "Tarifa de actividades",javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }
    
    public void showCampingFee(String message){
        javax.swing.JOptionPane.showMessageDialog(this, message, "Tarifa de campings",javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }

    // Getters para botones
    public JButton getFeeButtonQueryActivities() {
        return feeButtonQueryActivities;
    }

    public JButton getFeeButtonQueryCabin() {
        return feeButtonQueryCabin;
    }

    public JButton getFeeButtonQueryCamping() {
        return feeButtonQueryCamping;
    }

    public JButton getFeeButtonReturn() {
        return feeButtonReturn;
    }

    public JDialog getActivityFee() {
        return activityFee;
    }

    public JDialog getCabinFee() {
        return cabinFee;
    }

    public JDialog getCampingFee() {
        return campingFee;
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton feeButtonQueryActivities;
    private javax.swing.JButton feeButtonQueryCabin;
    private javax.swing.JButton feeButtonQueryCamping;
    private javax.swing.JButton feeButtonReturn;
    private javax.swing.JLabel feeTitle;
    // End of variables declaration//GEN-END:variables
}
