/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example.View;

import javax.swing.JButton;

/**
 *
 * @author negas
 */
public class ReserveView extends javax.swing.JFrame {

    /**
     * Creates new form ReserveView
     */
    public ReserveView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reserveTitle = new javax.swing.JLabel();
        reserveButtonAdd = new javax.swing.JButton();
        reserveButtonRemove = new javax.swing.JButton();
        reserveButtonSearchById = new javax.swing.JButton();
        reserveButtonSearchByFilter = new javax.swing.JButton();
        reserveButtonShowList = new javax.swing.JButton();
        reserveButtonEdit = new javax.swing.JButton();
        reserveButtonReturn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        reserveTitle.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        reserveTitle.setText("Gestion de Reservas");

        reserveButtonAdd.setText("Agregar");
        reserveButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveButtonAddActionPerformed(evt);
            }
        });

        reserveButtonRemove.setText("Eliminar");

        reserveButtonSearchById.setText("Buscar por id");
        reserveButtonSearchById.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveButtonSearchByIdActionPerformed(evt);
            }
        });

        reserveButtonSearchByFilter.setText("Buscar por filtro");

        reserveButtonShowList.setText("Lista Reservas");
        reserveButtonShowList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveButtonShowListActionPerformed(evt);
            }
        });

        reserveButtonEdit.setText("Editar");
        reserveButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveButtonEditActionPerformed(evt);
            }
        });

        reserveButtonReturn.setText("Salir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(reserveButtonReturn))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(reserveTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(reserveButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(reserveButtonRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(reserveButtonSearchById, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(reserveButtonSearchByFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(reserveButtonShowList, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(reserveButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(reserveTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reserveButtonAdd)
                    .addComponent(reserveButtonRemove))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reserveButtonSearchById)
                    .addComponent(reserveButtonSearchByFilter))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reserveButtonEdit)
                    .addComponent(reserveButtonShowList))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(reserveButtonReturn))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reserveButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveButtonEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reserveButtonEditActionPerformed

    private void reserveButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveButtonAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reserveButtonAddActionPerformed

    private void reserveButtonSearchByIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveButtonSearchByIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reserveButtonSearchByIdActionPerformed

    private void reserveButtonShowListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveButtonShowListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reserveButtonShowListActionPerformed
    
    // Getters para botones
    public JButton getReserveButtonAdd() {
        return reserveButtonAdd;
    }

    public JButton getReserveButtonRemove() {
        return reserveButtonRemove;
    }

    public JButton getReserveButtonReturn() {
        return reserveButtonReturn;
    }

    public JButton getReserveButtonSearchByFilter() {
        return reserveButtonSearchByFilter;
    }

    public JButton getReserveButtonSearchById() {
        return reserveButtonSearchById;
    }

    public JButton getReserveButtonShowList() {
        return reserveButtonShowList;
    }

    public JButton getReserveButtonEdit() {
        return reserveButtonEdit;
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton reserveButtonAdd;
    private javax.swing.JButton reserveButtonEdit;
    private javax.swing.JButton reserveButtonRemove;
    private javax.swing.JButton reserveButtonReturn;
    private javax.swing.JButton reserveButtonSearchByFilter;
    private javax.swing.JButton reserveButtonSearchById;
    private javax.swing.JButton reserveButtonShowList;
    private javax.swing.JLabel reserveTitle;
    // End of variables declaration//GEN-END:variables
}
